Name: DAOld-Backend
ListenOn: :8080
State: test
Auth:
  SecretKey: |
    -----BEGIN PRIVATE KEY-----
    MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDdsgGlcAZjPACM
    CJOOGu3Md+3BbzorhngBq69U/4v6VxxEOZKqL6szPuxrzvgz3eXQ+WvPHw7vUKyA
    +EU5jgPPYjVwGIeP/BTBw4o8G9tD6PWBWANyja0LMxfkVCYZwVUVX8SO0RpGPiQv
    Klp5UkeVBjdyxvQ6FZ+aO8VvVK80rxoio7HSs2fPDJBx31gKlXLPEmeNUkLBIbFe
    7ChaIduRRWHZ2/V0KEbrijbTqgiu8S8Kx08zyGI1zzGwyDPqI+V5TGLSt3j9JHew
    Tg9HdeDDZAJFdUIjpCAmuYks4VBLnA7xg6qqLg+na7YhZT7AcgwH7m8BKL+XwOov
    v1SIrnxzAgMBAAECggEABmUkpAOTw5gPAfsbWo2PT4ckHiDZwjiqTI4JzD9k589M
    evFYOD2QyDUn98IsKb7casdPI1XnheLDXyMKSCs/E+Pm27lxa6dfZ+l+mtZI4HAf
    aOBDlTHeDIUoSsdcpACONkQhdOc2RVF0lMG5g2dqtjNMNSzlDanjBT11KA1+0luu
    +qB0hywEfZFtPJi0gZqJQmytJAF25bH7CAXmGLKlK9Ump+kuox/0hNYOEP3uZe9l
    pZ4q9Y27KzfVDaGo3C1Cp+ZxMP5WN1b0JZQwxhxQbOPyr2CYpZSTvFjszW8yenA2
    vDaPlGGqu/TQmducy8PMulIAbWp9psZttZkWGoADcQKBgQDnFUm8gfjCWkJqq/h0
    LIcmMcvCfJKHFD76Z1SiaI73iB5sdbzxgT9RUUnW4YtzkNaebZu9z4+pW/TZL+nc
    dS99XHf44xoZl9Xw/3O5EIH48B1V5f+NUNExDNgkPekgB5S+q66YWTX4GVqny4XP
    vGO78e0SNHT9r5zXjDIzMIRPYwKBgQD1mZTXpHn21BCFge6YQ773GxWMZTumZMtT
    O/xBRpS8kMsU7yU86qMiUUDcp9hioFT8IW1NC5FArZKKIzNzTnsZNleMvv9Q80Pl
    4eUN7jk7jRTDWWVRZ+JlZTdt9SGAaZR1hYEkmt8pAbQWKoLs1PyTGX645Gkin8BX
    skV4ELfTsQKBgEIiMYwllk/pDQECXoTBCZzAu5PZmwXVoYCAehRQ4DmvVyWrPHvR
    hZF8NimtOv/D/+gvblcQRAkwLA7MS52wW/sAr8UnGZ0hezURpsjcFJZuAbdHr699
    5aCoEGOu5D0qbkNzVvB695sdhnhnItClFdYAEt0W7jR8QeLeWK+VvwgJAoGAVxWc
    B1KUxIaxTQWjWm47GleKLnv+yKNYzSyp52Nlfe9BcyzQ4Wa5bYOuIg+J1H7RY41e
    ukDtwidJnJ2asroTP/9az9cxpLx9SNfuZiAgPxNpV1Mtb84MIrPfEagntua482rh
    Pd+EXX/zISD1x5BF9srFej3TYamPhAj8RPR4miECgYABC7kJv95anr6+qpddisqf
    MbRR7itlWz131i0LdyJvjJ/lyDLk9FR0RTAsX9fa19oYEqnYpvP8VI4PcXhomlBK
    OYpYhsWCrsv4T380O9avfxjwq1vcvnfNwF4/0+Sg0mwZ3OyA5hJiP/lh6kgzSwGW
    PDtXCCuSpcv+hDoaVq8HwQ==
    -----END PRIVATE KEY-----
  PublicKey: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3bIBpXAGYzwAjAiTjhrt
    zHftwW86K4Z4AauvVP+L+lccRDmSqi+rMz7sa874M93l0Plrzx8O71CsgPhFOY4D
    z2I1cBiHj/wUwcOKPBvbQ+j1gVgDco2tCzMX5FQmGcFVFV/EjtEaRj4kLypaeVJH
    lQY3csb0OhWfmjvFb1SvNK8aIqOx0rNnzwyQcd9YCpVyzxJnjVJCwSGxXuwoWiHb
    kUVh2dv1dChG64o206oIrvEvCsdPM8hiNc8xsMgz6iPleUxi0rd4/SR3sE4PR3Xg
    w2QCRXVCI6QgJrmJLOFQS5wO8YOqqi4Pp2u2IWU+wHIMB+5vASi/l8DqL79UiK58
    cwIDAQAB
    -----END PUBLIC KEY-----
  AccessExpire: 86400

Log:
  Encoding: json
  Level: info
  Stat: false

Mongo:
  URL: "mongodb://noanamegroup:noanamegroup-daold@localhost:27018/?readConcernLevel=majority"
  DB: "daold"

Cache:
  - Host: "localhost:6380"
    Password: "noanamegroup-daold"

Redis:
  Host: "localhost:6380"
  Password: "noanamegroup-daold"
  DB: 0
