Name: Meowpick-Backend
ListenOn: :8080
State: test
Auth:
  SecretKey: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDC2r3yi0XFiE8o
    fB7xq73fqBWIyT655x3xoh2G/2FcrvHnNxfSAmALTM4ChtpcuO3bbDgDgsk0APz3
    4RPmQRkbzgBF1I88zePfQFcAhpAuvINKfzzR+oCylp+Cw+Wc7dFQJQ/NAdTkUetA
    eAAffoA1VhPZrc30Wa3iGx2A3pwn/97PxjmB/Sw87Z8aC1EU6f8nvELhTinLIv3K
    qjRZ2lQl8uwrBA9Q29OXWYsZQ9nYMAo+2CoGuV0xYDOPlR/HEHiPArXfVFFSi6pY
    kr5wGgFK7w6wxD0UEcej5FcnR/4fBncNAN+uRIIUqGQRifaOYhSc849OFtY2p72s
    RqWzOY8/AgMBAAECggEANqdAC93Aji0zdrmJvGNdeHQexiUcMOyAW5wLCChtWJ/B
    PgcX6VG9Oq4qQk8sxEEihh8Ofv2aDboROj2pZTXxIvle3jdGjdl6Bs53GLCllFZP
    xP93QbYvjufsibMEnkWeJgqfKfNPkVLg105RSoQi1dL08mNrlxPoT7knR1QpHJaM
    P5IQ6A4V1+WGIQXFZPXEkQLdl2oSGiRC84T7js50wmu+gkKSDeZN+t1KdDy9EFy6
    XgE7b+aDh/jNPeJkNFfTbJYMxiDU2cDqx9hoAPUTZZ+7nZ/eP4ChDNK90qQVenHG
    BxgiuSjUYGkKUdZ+L/D8qDAX6HLRrCp/gCZPGp/4UQKBgQD1kgf8xIGmZvxLNoIi
    vLDQSEG63zTU6PLZVqKMNptle6F/ydrOeIAjReENmwJyijt4kASCk11NPQisU/sv
    C560sAP4njhuAXaJ6BFOSN9iBxfrX2QWtD0A/84s/FunfXJwUHFuya2jd13t4X7R
    udeLbMqF4qUx+4ljChOjtqoo3QKBgQDLIUzsWo++6E6NbRrZIY8W4WFtUiBUWfPL
    /n1guYOuLDDu9LaMhB/qy0FvBBocuc5tfcE5FHbIFgowxDofp6PnhIHFMKcyWzlw
    pX51u5azSCRUhAxJCFwGJ3lCBMsUcbyS/m5hsd/oUWYN3V0PZ6yJVsErnbWEtxBD
    0Axp1rFIywKBgQCRj8kaRGTRfRQphRroek6Yd2w2193aImbo+1iIoknEgt78/2qq
    nnTd86ruRKbTvCp6UWvK9o0EnpwIghNPFKUzV25TLX4nfsiEAEJZ1ApNcgT0qOuM
    JbRPZlIRCllN06dE+fnzAKrjTXso6VQh/vXMGGWHrQvcr8wFH9D6ZulAJQKBgQCs
    pMfxVmM4Gc+xyhp4k1o/Ux1wQc3yg2V/avP7ApGVtj98yQZiVWWfNFOP3IepBI8b
    ZjeUoPz3wCu3GQBhqSTYgDmfdGOWnAws3quluuMxy039eyHJ7M3x+RjJcLN909E3
    igIdDIZGuPApNoyCrFXrgI272VXOz5yGVkxGpE+XkwKBgFi54ACGxgT2dtK4+gUM
    sa3eWCsA+Maifn634unHgH5heEWPbDgZBshXE7ZEkpzMzeCoD6CxCXvXuwngcbMG
    v00EJdJdhunMwVGRXtq3x6dOTUI371r9fK548wx4kcXkOmXmqvXFINwHKBjH2vGs
    LwrvZWSGKarLV19QwE74Lgyk
    -----END PRIVATE KEY-----
  PublicKey: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwtq98otFxYhPKHwe8au9
    36gViMk+uecd8aIdhv9hXK7x5zcX0gJgC0zOAobaXLjt22w4A4LJNAD89+ET5kEZ
    G84ARdSPPM3j30BXAIaQLryDSn880fqAspafgsPlnO3RUCUPzQHU5FHrQHgAH36A
    NVYT2a3N9Fmt4hsdgN6cJ//ez8Y5gf0sPO2fGgtRFOn/J7xC4U4pyyL9yqo0WdpU
    JfLsKwQPUNvTl1mLGUPZ2DAKPtgqBrldMWAzj5UfxxB4jwK131RRUouqWJK+cBoB
    Su8OsMQ9FBHHo+RXJ0f+HwZ3DQDfrkSCFKhkEYn2jmIUnPOPThbWNqe9rEalszmP
    PwIDAQAB
    -----END PUBLIC KEY-----
  AccessExpire: 86400
Log:
  Encoding: json
  Level: info
  Stat: false
Mongo:
#  URL: "mongodb://boyuan-meowpick:boyuan-it-club-meowpick@localhost:27017/your_db?authSource=admin"
  URL: "mongodb://localhost:27017"
  DB: "meowpick"
Cache:
  - Host: "localhost:6379"
    Password: "boyuan-it-club-meowpick"
Redis:
  Host: "localhost:6379"
  Password: "boyuan-it-club-meowpick"
  DB: 0