// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	"github.com/NoANameGroup/DAOld-Backend/internal/config"
	"github.com/NoANameGroup/DAOld-Backend/internal/repository"
	"github.com/NoANameGroup/DAOld-Backend/internal/service"
)

// Injectors from wire.go:

func NewProvider() (*Provider, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewRepository(configConfig)
	userService := service.UserService{
		UserMapper: userRepository,
	}
	providerProvider := &Provider{
		Config:      configConfig,
		UserService: userService,
	}
	return providerProvider, nil
}
